### PR TITLE
Add new possibilities for user customization

### PR DESCRIPTION
**Pull request by substring**
- loads an overlay configuration file if available as `/recalbox/share/overlays/<system>/<rom>.cfg` if the file exists
- can append a `/recalbox/share/system/configs/retroarch/<system>.cfg` file to retroarch config for a per system custom config if the file exists
- can append a `/recalbox/share/system/configs/retroarch/<system>/<rom>.cfg` file to retroarch config for a per game custom config if the file exists
- handle the new system.es.videomode in recalbox.conf to set the resolution once leaving the emulator

In both cases rom = rom file name + extension. For ex : commando.zip, so the expected cfg file is commando.zip.cfg

### CODE REVIEW

**Comment by substring** [comment]
As @digitalLumberjack  pointed out, can't add multiple --append. Instead we should add them sperated by a |

Tested, works fine. Can't tell which file takes precedence over others if a same option is repeated multiple times through all files. But why care, this PR if for power users

**Comment by digitalLumberjack** [comment]
That would be nice to let the game cfg overload the system cfg. That can allow people to set default options in the system.

**Comment by substring** [comment]
In that case you can't have generic settings for a system and need to apply it again on all cfg'ed games. That's why i set it this way. But i think the last file overloaded settings is the one to be kept. Will ask the retroarch guyz

And remember those settings wouldn't even be considered when using the current custom configs from recalbox.conf

**Comment by digitalLumberjack** [comment]
You can test. Set a 16/9 ratio in snes.cfg and a 4/3 in Super MarioWorld.cfg.
In the case i describe, we need a 16/9 for an other game and 4/3 for super mario world.
If it doesn't work that way change the oredre of the files in configgen, and we will see if the order is taken in account.

**Comment by substring** [comment]
I did it with the menu_driver option :
- in snes.cfg `menu_driver = "xmb"`
- in DonkeyKongClassic (Shiru).smc.cfg `menu_driver = "glui"`

The menu_driver was the one retained from the last config file, which is the game.cfg. So yes, retroarch always keeps the last option it would find.

**Comment by digitalLumberjack** [comment]
Good job

**Pull request merged**
