### PR TITLE
Draw FPS on supported emulators

### PR DESCRIPTION
**Pull request by substring**
When activating the "Draw Framerate" in ES, this will also show FPS in emulators that support it. So far :
- retroarch
- ppsspp
- mupen (missing the odroid video plugin on my side)

Also solved a few bugs here and there

### CODE REVIEW

**Comment by rockaddicted** [comment]
mupen64plus can't display information on the screen, if this one is running in opengl mode.

**Comment by substring** [comment]
That depends on the video plugin. On C2/XU4, @nadenislamarre used a plugin that can support it, which we don't use on Pi. He'll add it once this PR is merged i think

**Comment by rockaddicted** [comment]
nope, plugin video may have an option to display the fps, but mupen64plus-core, won't display it, if running in openglmode, even if this option is activated in the video plugin option.
It is a known issue of mupen64plus emulator.

**Comment by nadenislamarre** [comment]
nice job.
i'll adapt with show_fps for mupen64plus-video-glide64mk2 once merged (used on xu4, c2, x86 and x86_64) and configs/dolphin-emu/Config/dolphin.ini

**Comment by paradadf** [comment]
@nadenislamarre is there a reason why gliden64 isn't the default emulator for the new archs?

**Comment by nadenislamarre** [comment]
@paradadf yes. mupen64plus-video-glide64mk2 is the first one that compiled without any difficulty ;-) but of course, the others can probably added ; i've just spent no time on it.

**Comment by paradadf** [comment]
ahh ok, thanks for the heads-up!

**Comment by substring** [comment]
damn ... I have to take out the code from the Emulator class and put it in the ConfigManager. Still, I believe it's a messy way of doing it, as the methods from from ConfigManager should rather belong to the Emulator class

@digitalLumberjack what do you think if I merge the two classes ConfigManager and Emulator into Emulator, and I set my lateInit() method to replace the ConfigManager.configure() ?

**Comment by substring** [comment]
damn ... I have to take out the code from the Emulator class and put it in the ConfigManager. Still, I believe it's a messy way of doing it, as the methods from from ConfigManager should rather belong to the Emulator class

@digitalLumberjack what do you think if I merge the two classes ConfigManager and Emulator into Emulator, and I set my lateInit() method to replace the ConfigManager.configure() ?

**Comment by substring** [comment]
@digitalLumberjack please review

**Comment by digitalLumberjack** [comment]
great.

**Pull request merged**
