### PR TITLE
Set mupen resolution to n64.videomode

### PR DESCRIPTION
**Pull request by substring**
Solves https://github.com/recalbox/recalbox-os/issues/662#issuecomment-182327416
Needs testing
Took the opportunity to move emulator configuration specific routines to a new mupenConfig.py

### CODE REVIEW

**Comment by substring** [comment]
Don't merge yet, forgot to remove some debug messages

**Comment by substring** [comment]
@digitalLumberjack Now you can merge :)

**Comment by digitalLumberjack** [comment]
What happens if i set 1920*1080 for n64 ?

**Comment by substring** [comment]
It's wide and slow

**Comment by digitalLumberjack** [comment]
okay. hum. ok

**Pull request merged**
