### PR TITLE
Implementation of user's configuration files upgrade

### PR DESCRIPTION
**Pull request by LaurentMarchelli**
First step of a smart upgrade for configuration files.
Each generators must be responsible of the user's configuration file upgrade.
The next step will be into buildroot, S11Share.

### CODE REVIEW

**Comment by substring** [comment]
Do you mean configuration files that are supposed to be stored in ~/system/configs ?

What's the point of doing so when we didn't manage yet a way to update recalbox.conf ?

Next : why not set some default ancestors mehods that could do the very basic you wrote for lineapple : look for (option = value) and update only new.options as this could be the very first usage ? To my knowledge mupen, dosbox, retroarch and moonlight all have their config files written this way

I mean , the principle of updating "option = value" has a bigger dimension than just configgen, but almost the whole system

**Comment by LaurentMarchelli** [comment]
Hi, no it is not a problem of file location, it is a problem of responsibility.
As each generator manage the modification of emulation configuration files before running the emulator, they should also take care of upgrades (new parameters for instance).

As you know, every files in recalbox/share_init will be upgraded with the default template version, after you just have to apply needed modifications to recalbox/share files.

Generator configuration files should be upgraded by Generators, if recalbox.conf should also be upgraded, it may be done the emulatorlaucher.config_upgrade, for instance. 
And now, there is an entry point to do it.

Good point for for the ancestor, put it in Generator would be a good idea. 
As I do not have your knowledge about others generator, I guess you are the right person to do it.
Aren't you ?

**Comment by substring** [comment]
I just wrote 2 of them without knowing python lol so it's ugly but works anyway. 

So far, despite my quite young experience in the project, such a thing never happened.

Anyway @digitallumberjack will review your work and have his opinion ;)

Remember generators write config files at every launch of the emulator, so files are rewritten upon every new game. UNLESS the user specified a custom file.

**Comment by LaurentMarchelli** [comment]
No offense, nothing personal, I'm about one month old on the project and I do not have enough knowledge on others emulators to be able to modify existing code without taking the risk of a major regression. It was my point. 
I thought you could help, obviously not. What a pity !
Regards, ;-)

**Comment by digitalLumberjack** [comment]
That's a good implementation, but effectively, we never had the case. I merge it, it could be useful soon.

**Comment by LaurentMarchelli** [comment]
You're right, It will be useful soon, at least for linapple, i'm modifying the software to have a better joystick support. (save and load the game, some keys emulations from the joystick). ;-)

**Pull request merged**
