### PR TITLE
n64: change default deadzone from 4096 to 0

### PR DESCRIPTION
**Pull request by nadenislamarre**
not sure it works 100% please reread/retest.

007 just becomes playable.
the pad is really more sensitve and precise for several games.
i've no soucy with a 0 deadzone.
But for people who go soucy, i make it customisable.
Please double check this commit while the n64 configuration looks wired to me,
so, i'm not sure to not add a bug, even if i've a tested several things.

Signed-off-by: Nicolas Adenis-Lamarre <nicolas.adenis.lamarre@gmail.com>

### CODE REVIEW

**Comment by substring** [comment]
who had a problem with the deadzone so far ?

**Comment by nadenislamarre** [comment]
i just guess that if that is here it is perhaps not hazard

**Comment by substring** [comment]
the input.xml is not a bad idea : people unhappy with how buttons are set can customize it themselves, even more with the weirdest pad ever made on a console ;)
Anyway, in 4.1, i should rewrite a part of this configgen and try to set directly pads in the mupen64plus.cfg so we might be able to finally get a hand on players/pads order

**Comment by nadenislamarre** [comment]
this xml is used for kodi too.
note that this file is upgradable, because just in share_init by default.
note that the main subject of this issue is to default the deadzone to 0 to
make some games playable (007 for example).

**Pull request merged**
