### PR TITLE
4.1.x lineapple

### PR DESCRIPTION
**Pull request by digitalLumberjack**
@LaurentMarchelli i merge your code on the 4.1.X branch, can you review this merge and tell me if it's ok ?

### CODE REVIEW

**Comment by LaurentMarchelli** [comment]
I gonna have a look and I'll tell u.

**Comment by LaurentMarchelli** [comment]
Merge is fine, u can go.

**Comment by digitalLumberjack** [comment]
Thx

**Comment by LaurentMarchelli** [comment]
Welcome, thx 2 u. 
During the check, I found a bug in my tests, I guess I didn't test my tests enough :-D.
I gonna push a fix.

**Pull request merged**
