### PR TITLE
ES to Emulator Seperation

### PR DESCRIPTION
**Pull request by Omnija**
Without separating the emulators, creating seperate folders would causes issues with launching games or scraping properly.

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
Means we must add themes for ES (containing backgrounds, music, and logo) and change the es_system.xml file to take that in account

**Comment by rockaddicted** [comment]
Humm don't forget than when ES's Vram is overloaded, ES crash on boot. This happen when we activate too many systems in ES (not a recalbox's specific problem). So actually, we can't ever activated all systems in the same time with Zoid theme, and we are borderline with Simplight theme (the default one). And we have some new systems to add in recalbox 4.4.0

I think the best way to separate ngp/ngpc & wswan/wswancolor systems in ES, is to create subfolders in roms folders, and using a unique system in ES.

**Comment by digitalLumberjack** [comment]
Yes you're right @rockaddicted but i'm letting that happen because the future themes will not have this issues, and we will have prepared systems.

**Comment by nadenislamarre** [comment]
If we do the following, could it help ? :
- make sure only 5 screens are loaded in es at a time (current, 2 before, 2 after ; 2 or 1)
- and when you move, at the end of the animation, you unload 1 and load a new 1

Not sure it's easy to do, but i'm just finding if there were a solution to that long issue.

**Comment by digitalLumberjack** [comment]
We could do that, but we are creating themes that do not have backgrounds for each system. The system specific items will be display in overlap on the main background. As they are in svg, it doesn't take much memory.

**Comment by nadenislamarre** [comment]
Nice ;-)

2015-12-31 13:49 GMT+01:00 digitalLumberjack <notifications@github.com>:

**Comment by digitalLumberjack** [comment]
I close, the new theme did that

**Pull request closed without merging**
